import React, { useState, useRef } from "react";
import { motion, useScroll, useTransform, AnimatePresence } from "framer-motion";
import { ChevronDown, Anchor, ShieldCheck, Compass, Info, CheckCircle2, ChevronRight, Menu, X, ArrowRight } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { HoverCard, HoverCardContent, HoverCardTrigger } from "@/components/ui/hover-card";
import { Drawer, DrawerContent, DrawerTrigger, DrawerClose } from "@/components/ui/drawer";

// --- SECTIONS ---

const Navbar = () => {
  const [scrolled, setScrolled] = useState(false);

  React.useEffect(() => {
    const handleScroll = () => setScrolled(window.scrollY > 50);
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const links = ["Philosophy", "Vessel", "Journey", "Crew", "Booking"];

  return (
    <>
    <header
      className={`fixed top-0 w-full z-40 transition-all duration-500 border-b ${
        scrolled ? "bg-background/80 backdrop-blur-md border-border/50 py-4" : "bg-transparent border-transparent py-6"
      }`}
    >
      <div className="container mx-auto px-6 grid grid-cols-3 items-center">
        {/* Left: Logo */}
        <div className="flex items-center gap-2">
          <Anchor className="w-6 h-6 text-primary" />
          <span className="font-serif font-bold text-xl tracking-wider text-foreground">
            EXPEDITION<span className="text-primary">2</span>
          </span>
        </div>

        {/* Centre: Nav links */}
        <nav className="hidden md:flex items-center justify-center gap-8">
          {links.map((link) => (
            <a
              key={link}
              href={`#${link.toLowerCase()}`}
              className="text-sm uppercase tracking-widest text-muted-foreground hover:text-primary transition-colors"
            >
              {link}
            </a>
          ))}
        </nav>

        {/* Right: CTA */}
        <div className="hidden md:flex justify-end">
          <Button variant="outline" className="border-primary text-primary hover:bg-primary hover:text-primary-foreground rounded-none" asChild>
            <a href="#booking" data-testid="link-request-briefing">Request Briefing</a>
          </Button>
        </div>
      </div>
    </header>
    
    {/* Mobile Bottom Navigation (Visible only on small screens) */}
    <div className="md:hidden fixed bottom-6 inset-x-6 z-50">
      <div className="bg-card/90 backdrop-blur-md border border-primary/20 rounded-2xl flex items-center justify-between p-2 px-6 shadow-[0_10px_40px_rgba(0,0,0,0.5)]">
        <span className="font-serif text-sm tracking-wider">E2 Manifest</span>
        <Drawer>
          <DrawerTrigger asChild>
            <Button variant="ghost" size="sm" className="text-primary gap-2" data-testid="btn-mobile-menu">
              <Menu className="w-5 h-5" />
              <span className="text-xs uppercase tracking-widest">Menu</span>
            </Button>
          </DrawerTrigger>
          <DrawerContent className="bg-card border-t-primary/20">
            <div className="p-6 flex flex-col gap-6">
              <div className="flex justify-between items-center mb-4">
                <span className="font-serif font-bold text-lg">NAVIGATION</span>
                <DrawerClose asChild>
                  <Button variant="ghost" size="icon">
                    <X className="w-5 h-5" />
                  </Button>
                </DrawerClose>
              </div>
              {links.map((link) => (
                <DrawerClose asChild key={link}>
                  <a
                    href={`#${link.toLowerCase()}`}
                    className="text-xl font-serif tracking-wide border-b border-border/20 pb-4 text-foreground flex justify-between items-center"
                  >
                    {link}
                    <ChevronRight className="w-4 h-4 text-primary" />
                  </a>
                </DrawerClose>
              ))}
              <DrawerClose asChild>
                <Button className="w-full mt-4 h-14 text-lg" asChild>
                  <a href="#booking">Request Briefing</a>
                </Button>
              </DrawerClose>
            </div>
          </DrawerContent>
        </Drawer>
      </div>
    </div>
    </>
  );
};

const Hero = () => {
  return (
    <section className="relative h-[100dvh] flex items-center justify-center overflow-hidden">
      {/* Background Image generated by tool */}
      <div className="absolute inset-0 z-0">
        <img
          src="/images/hero.jpg"
          alt="Submarine descending into abyss"
          className="w-full h-full object-cover opacity-60"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-background via-background/40 to-transparent" />
      </div>

      <div className="container mx-auto px-6 relative z-10 text-center flex flex-col items-center">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 1, delay: 0.2 }}
          className="inline-flex items-center gap-2 px-4 py-2 border border-primary/30 bg-background/40 backdrop-blur-sm mb-8"
        >
          <div className="w-2 h-2 rounded-full bg-primary animate-pulse" />
          <span className="text-xs uppercase tracking-[0.3em] text-primary">Now accepting 2025 manifests</span>
        </motion.div>

        <motion.h1
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 1, delay: 0.4 }}
          className="text-5xl md:text-7xl lg:text-8xl font-serif font-bold text-foreground max-w-5xl leading-[1.1] mb-6"
        >
          BEYOND THE <span className="text-transparent bg-clip-text bg-gradient-to-b from-foreground to-primary/50 text-glow">ABYSS</span>
        </motion.h1>

        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 1, delay: 0.6 }}
          className="text-lg md:text-xl text-muted-foreground max-w-2xl mb-12 font-light"
        >
          The rarest experience on Earth. A pressurized descent to the hadal zone, past bioluminescent mysteries and untouched wrecks.
        </motion.p>

        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.5, delay: 0.8 }}
        >
          <Button size="lg" className="rounded-none text-lg h-14 px-8 tracking-wide font-medium bg-primary text-primary-foreground hover:bg-white hover:text-black transition-all" asChild>
            <a href="#booking" data-testid="btn-hero-booking">Initiate Descent</a>
          </Button>
        </motion.div>
      </div>

      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 1.5, duration: 1 }}
        className="absolute bottom-10 left-1/2 -translate-x-1/2 flex flex-col items-center gap-2"
      >
        <span className="text-xs uppercase tracking-widest text-muted-foreground">Descend</span>
        <ChevronDown className="w-5 h-5 text-primary animate-bounce" />
      </motion.div>
    </section>
  );
};

const Philosophy = () => {
  return (
    <section id="philosophy" className="py-32 bg-background relative border-t border-border/10">
      <div className="container mx-auto px-6">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
          <motion.div
            initial={{ opacity: 0, x: -30 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.8 }}
          >
            <h2 className="text-3xl md:text-5xl font-serif font-bold mb-8 leading-tight">
              Where Extreme Science <br/> Meets <span className="text-primary">Absolute Silence</span>.
            </h2>
            <div className="space-y-6 text-muted-foreground font-light text-lg">
              <p>
                We are not a tourist operation. Expedition 2 exists at the intersection of deep-sea research and ultra-luxury exploration.
              </p>
              <p>
                At 36,000 feet below the surface, the ocean is an alien world. The pressure is crushing, the darkness is absolute, and the life is entirely unfamiliar. We bring the light, the safety, and the unmatched comfort of a master-crafted vessel.
              </p>
            </div>
            
            <div className="mt-12 grid grid-cols-2 gap-8">
              <div>
                <div className="text-4xl font-serif text-foreground mb-2">11k</div>
                <div className="text-sm text-primary uppercase tracking-widest">Meters Depth</div>
              </div>
              <div>
                <div className="text-4xl font-serif text-foreground mb-2">3</div>
                <div className="text-sm text-primary uppercase tracking-widest">Guests per Dive</div>
              </div>
            </div>
          </motion.div>
          
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            transition={{ duration: 1 }}
            className="relative aspect-square md:aspect-[4/3] w-full bg-card p-2 border border-border/30"
          >
            <img src="/images/depth.jpg" alt="Deep ocean hydrothermal vent" className="w-full h-full object-cover filter contrast-125" />
            <div className="absolute -bottom-6 -left-6 bg-card border border-primary/20 p-6 max-w-[250px] shadow-2xl backdrop-blur-md">
              <Compass className="w-8 h-8 text-primary mb-4" />
              <p className="text-sm text-muted-foreground">
                "An environment less explored than the surface of the moon."
              </p>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
};

const Vessel = () => {
  return (
    <section id="vessel" className="py-32 bg-card relative">
      <div className="container mx-auto px-6">
        <div className="text-center mb-20">
          <span className="text-primary uppercase tracking-widest text-sm mb-4 block">The Instrument</span>
          <h2 className="text-4xl md:text-5xl font-serif font-bold">E2 Leviathan Class</h2>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
          <div className="lg:col-span-7 relative group">
            <img src="/images/vessel.jpg" alt="Submarine exterior" className="w-full h-[600px] object-cover border border-border/30" />
            
            {/* Interactive Hotspots via HoverCards */}
            <div className="absolute inset-0">
              <HoverCard>
                <HoverCardTrigger asChild>
                  <button className="absolute top-[30%] left-[40%] w-8 h-8 rounded-full bg-primary/20 border border-primary flex items-center justify-center group-hover:scale-110 transition-transform">
                    <div className="w-2 h-2 bg-primary rounded-full animate-ping" />
                  </button>
                </HoverCardTrigger>
                <HoverCardContent className="w-80 bg-background/95 backdrop-blur-lg border-primary/50">
                  <div className="flex justify-between space-x-4">
                    <div className="space-y-1">
                      <h4 className="text-sm font-semibold text-primary uppercase tracking-wider">Optically Perfect Viewport</h4>
                      <p className="text-sm text-muted-foreground">
                        90mm thick acrylic sphere offering a distortion-free 360° view of the abyss, engineered to withstand 1,500 atmospheres.
                      </p>
                    </div>
                  </div>
                </HoverCardContent>
              </HoverCard>

              <HoverCard>
                <HoverCardTrigger asChild>
                  <button className="absolute top-[60%] left-[70%] w-8 h-8 rounded-full bg-primary/20 border border-primary flex items-center justify-center group-hover:scale-110 transition-transform">
                    <div className="w-2 h-2 bg-primary rounded-full animate-ping" />
                  </button>
                </HoverCardTrigger>
                <HoverCardContent className="w-80 bg-background/95 backdrop-blur-lg border-primary/50">
                  <div className="flex justify-between space-x-4">
                    <div className="space-y-1">
                      <h4 className="text-sm font-semibold text-primary uppercase tracking-wider">Silent Thrusters</h4>
                      <p className="text-sm text-muted-foreground">
                        Six-axis omnidirectional electric propulsion. Zero emissions, zero acoustic pollution, allowing close approach to sensitive marine life.
                      </p>
                    </div>
                  </div>
                </HoverCardContent>
              </HoverCard>
            </div>
          </div>

          <div className="lg:col-span-5 flex flex-col justify-center">
            <h3 className="text-2xl font-serif mb-6">Technical Specifications</h3>
            <p className="text-muted-foreground mb-8">
              Every component is obsessively engineered for survival in an environment that actively wants to crush it. Click to expand systems details.
            </p>
            
            <Accordion type="single" collapsible className="w-full">
              <AccordionItem value="item-1">
                <AccordionTrigger>Pressure Hull</AccordionTrigger>
                <AccordionContent>
                  Constructed from a proprietary titanium alloy (Ti-6Al-4V ELI), machined to a tolerance of 0.05mm. Tested to 150% of the Marianas Trench pressure. It ensures absolute safety while maintaining standard atmospheric pressure inside. No decompression sickness.
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-2">
                <AccordionTrigger>Life Support Systems</AccordionTrigger>
                <AccordionContent>
                  Quad-redundant closed-loop O2 scrubbers. 96 hours of emergency reserve life support for 4 occupants. Continuous cabin monitoring for CO2, humidity, and temperature.
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-3">
                <AccordionTrigger>Comms & Navigation</AccordionTrigger>
                <AccordionContent>
                  Through-water acoustic modems transmitting telemetry, voice, and vital stats to the surface mothership every 10 seconds. Synthetic aperture sonar for mapping the pitch-black floor.
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </div>
        </div>
      </div>
    </section>
  );
};

const DepthJourney = () => {
  const containerRef = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ["start center", "end center"]
  });

  const zones = [
    { name: "Epipelagic", depth: "200m", desc: "The Sunlight Zone. Where 90% of ocean life resides. Light begins to fade rapidly." },
    { name: "Mesopelagic", depth: "1,000m", desc: "The Twilight Zone. Bioluminescence begins. Giant squid and lanternfish." },
    { name: "Bathypelagic", depth: "4,000m", desc: "The Midnight Zone. Complete darkness. Crushing pressure. Sperm whales hunt." },
    { name: "Abyssopelagic", depth: "6,000m", desc: "The Abyss. Near freezing. A barren expanse of sediment and ancient wrecks." },
    { name: "Hadalpelagic", depth: "11,000m", desc: "The Trenches. The destination. Alien extremophiles living off hydrothermal vents." },
  ];

  return (
    <section id="journey" ref={containerRef} className="py-32 bg-background relative border-y border-border/10">
      <div className="container mx-auto px-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-16">
          <div className="md:sticky md:top-32 h-fit">
            <h2 className="text-4xl md:text-5xl font-serif font-bold mb-6">The Descent</h2>
            <p className="text-muted-foreground text-lg mb-8">
              A 4-hour freefall through the layers of the ocean. Watch the color drain from the world as you enter the void.
            </p>
            <div className="relative h-64 w-full bg-card border border-border/30 overflow-hidden hidden md:block">
              {/* Visual representation of depth color changing based on scroll */}
              <motion.div 
                className="absolute inset-0 bg-gradient-to-b from-[#0a84ff] via-[#001f3f] to-black"
                style={{ y: useTransform(scrollYProgress, [0, 1], ["0%", "-80%"]) }}
              />
              <div className="absolute inset-0 bg-[url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0IiBoZWlnaHQ9IjQiPjxyZWN0IHdpZHRoPSI0IiBoZWlnaHQ9IjQiIGZpbGw9IiNmZmZmZmYiIGZpbGwtb3BhY2l0eT0iMC4wNSIvPjwvc3ZnPg==')] opacity-50" />
            </div>
          </div>

          <div className="space-y-24">
            {zones.map((zone, idx) => (
              <motion.div 
                key={zone.name}
                initial={{ opacity: 0, x: 50 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true, margin: "-100px" }}
                transition={{ duration: 0.6 }}
                className="relative pl-8 border-l-2 border-primary/20"
              >
                <div className="absolute -left-[9px] top-0 w-4 h-4 bg-background border-2 border-primary rounded-full" />
                <div className="text-sm font-mono text-primary mb-2">{zone.depth}</div>
                <h3 className="text-3xl font-serif mb-4 text-foreground">{zone.name}</h3>
                <p className="text-muted-foreground">{zone.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

const TrustAndCrew = () => {
  return (
    <section id="crew" className="py-32 bg-card">
      <div className="container mx-auto px-6">
        <div className="flex flex-col md:flex-row justify-between items-end mb-16 gap-8">
          <div>
            <span className="text-primary uppercase tracking-widest text-sm mb-4 block">The Manifest</span>
            <h2 className="text-4xl md:text-5xl font-serif font-bold">Your Guides to the Deep</h2>
          </div>
          <div className="flex items-center gap-4 bg-background/50 p-4 border border-primary/20 backdrop-blur">
            <ShieldCheck className="w-8 h-8 text-primary" />
            <div>
              <div className="text-sm font-bold">DNV-GL Certified</div>
              <div className="text-xs text-muted-foreground">Class +1A1 Submersible</div>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
          <div className="bg-background border border-border/50 p-6 group hover:border-primary/50 transition-colors">
            <div className="aspect-[4/3] w-full overflow-hidden mb-6 bg-muted">
              <img src="/images/pilot.jpg" alt="Chief Pilot" className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700" />
            </div>
            <div className="text-sm text-primary uppercase tracking-widest mb-1">Chief Pilot</div>
            <h3 className="text-2xl font-serif mb-3">Elena Rostova</h3>
            <p className="text-muted-foreground text-sm">
              Former naval test pilot with over 3,000 logged hours in deep-submergence vehicles. Elena has navigated the Marianas Trench five times.
            </p>
          </div>

          <div className="bg-background border border-border/50 p-6 group hover:border-primary/50 transition-colors">
            <div className="aspect-[4/3] w-full overflow-hidden mb-6 bg-muted">
              {/* Just reusing pilot image as placeholder for scientist, or we could generate another. Using eco.jpg as an abstract representation or another image */}
              <img src="/images/eco.jpg" alt="Lead Biologist" className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700 opacity-80" />
            </div>
            <div className="text-sm text-primary uppercase tracking-widest mb-1">Lead Biologist</div>
            <h3 className="text-2xl font-serif mb-3">Dr. Aris Thorne</h3>
            <p className="text-muted-foreground text-sm">
              World-renowned expert in hadal-zone extremophiles. Dr. Thorne guides the scientific mission of every dive, identifying species never before seen.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

const WhatToExpect = () => {
  return (
    <section className="py-32 bg-background">
      <div className="container mx-auto px-6">
        <div className="text-center mb-16">
          <h2 className="text-4xl font-serif font-bold mb-4">What to Expect</h2>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            A journey to the bottom of the ocean requires preparation. Here is your timeline.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {[
            { step: "01", title: "Physical Prep", desc: "A comprehensive medical review and 2 days of G-force and confinement familiarization at our surface facility." },
            { step: "02", title: "The Briefing", desc: "Review the target topography, mission objectives, and emergency protocols with your pilot and crew." },
            { step: "03", title: "The 12-Hour Dive", desc: "4 hours down. 4 hours on the bottom exploring. 4 hours ascent. A grueling but transformative day." }
          ].map((item) => (
            <div key={item.step} className="p-8 border border-border/30 relative overflow-hidden group">
              <div className="absolute top-0 right-0 p-4 text-6xl font-serif text-muted/20 group-hover:text-primary/10 transition-colors">{item.step}</div>
              <h3 className="text-xl font-serif mb-4 relative z-10">{item.title}</h3>
              <p className="text-muted-foreground text-sm relative z-10">{item.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

const Sustainability = () => {
  return (
    <section className="py-24 bg-card border-y border-border/10">
      <div className="container mx-auto px-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
          <div className="order-2 md:order-1">
            <h2 className="text-3xl md:text-4xl font-serif font-bold mb-6">Leave No Trace</h2>
            <p className="text-muted-foreground mb-6">
              The deep ocean is the most fragile ecosystem on our planet. Expedition 2 operates with a strictly zero-impact mandate.
            </p>
            <ul className="space-y-4">
              {[
                "100% Electric, silent propulsion to avoid acoustic trauma.",
                "Zero physical contact with the seabed or hydrothermal vents.",
                "15% of all expedition fees fund the Hadal Conservation Trust."
              ].map((text, i) => (
                <li key={i} className="flex items-start gap-3">
                  <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                  <span className="text-sm text-foreground">{text}</span>
                </li>
              ))}
            </ul>
          </div>
          <div className="order-1 md:order-2 flex justify-center">
            <div className="w-48 h-48 md:w-64 md:h-64 rounded-full overflow-hidden border-4 border-primary/20 shadow-[0_0_50px_rgba(0,180,255,0.2)]">
              <img src="/images/eco.jpg" alt="Glowing jellyfish" className="w-full h-full object-cover" />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

const Booking = () => {
  const [status, setStatus] = useState<"idle" | "submitting" | "success">("idle");

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setStatus("submitting");
    // Simulate API call
    setTimeout(() => setStatus("success"), 1500);
  };

  return (
    <section id="booking" className="py-32 bg-background relative overflow-hidden">
      {/* Decorative bg */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] bg-primary/5 rounded-full blur-[100px] pointer-events-none" />
      
      <div className="container mx-auto px-6 relative z-10 max-w-2xl">
        <div className="text-center mb-12">
          <h2 className="text-4xl font-serif font-bold mb-4">Request a Briefing</h2>
          <p className="text-muted-foreground">
            Manifest spots are strictly limited to 12 guests per year. Submit your details to schedule a private consultation.
          </p>
        </div>

        {status === "success" ? (
          <motion.div 
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            className="bg-card border border-primary/30 p-8 text-center"
          >
            <CheckCircle2 className="w-16 h-16 text-primary mx-auto mb-6" />
            <h3 className="text-2xl font-serif mb-2">Transmission Received</h3>
            <p className="text-muted-foreground">
              Our manifest director will contact you via secure channel within 24 hours to arrange your briefing.
            </p>
          </motion.div>
        ) : (
          <form onSubmit={handleSubmit} className="space-y-6 bg-card p-8 md:p-10 border border-border/50 shadow-2xl relative">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-2">
                <Label htmlFor="firstName">First Name</Label>
                <Input id="firstName" required className="bg-background" data-testid="input-firstname" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="lastName">Last Name</Label>
                <Input id="lastName" required className="bg-background" data-testid="input-lastname" />
              </div>
            </div>
            
            <div className="space-y-2">
              <Label htmlFor="email">Secure Email</Label>
              <Input id="email" type="email" required className="bg-background" data-testid="input-email" />
            </div>

            <div className="space-y-2">
              <Label htmlFor="intent">Reason for Expedition</Label>
              <textarea 
                id="intent" 
                required 
                className="flex min-h-[100px] w-full border border-border/50 bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                placeholder="Briefly describe your motivation..."
                data-testid="input-intent"
              />
            </div>

            <Button 
              type="submit" 
              className="w-full h-14 text-lg mt-4" 
              disabled={status === "submitting"}
              data-testid="btn-submit-booking"
            >
              {status === "submitting" ? (
                <div className="flex items-center gap-2">
                  <div className="w-4 h-4 border-2 border-background border-t-transparent rounded-full animate-spin" />
                  Encrypting...
                </div>
              ) : (
                "Initiate Contact"
              )}
            </Button>
          </form>
        )}
      </div>
    </section>
  );
};

const Footer = () => {
  return (
    <footer className="bg-[#02050a] py-12 border-t border-border/20">
      <div className="container mx-auto px-6">
        <div className="flex flex-col md:flex-row justify-between items-center gap-6">
          <div className="flex items-center gap-2">
            <Anchor className="w-5 h-5 text-primary" />
            <span className="font-serif font-bold tracking-wider text-muted-foreground">
              EXPEDITION<span className="text-primary">2</span>
            </span>
          </div>
          <div className="flex gap-6 text-sm text-muted-foreground/60">
            <a href="#" className="hover:text-primary transition-colors">Terms of Descent</a>
            <a href="#" className="hover:text-primary transition-colors">Privacy</a>
            <a href="#" className="hover:text-primary transition-colors">DNV-GL Registry</a>
          </div>
          <div className="text-xs text-muted-foreground/40">
            © {new Date().getFullYear()} Expedition 2 Operations Ltd.
          </div>
        </div>
      </div>
    </footer>
  );
};

export default function Home() {
  return (
    <main className="min-h-screen bg-background relative selection:bg-primary/30 selection:text-primary-foreground text-foreground">
      {/* Global CSS noise overlay via tailwind plugin/class defined in index.css */}
      <div className="fixed inset-0 noise-overlay z-[100]"></div>
      
      <Navbar />
      <Hero />
      <Philosophy />
      <Vessel />
      <DepthJourney />
      <TrustAndCrew />
      <WhatToExpect />
      <Sustainability />
      <Booking />
      <Footer />
      
    </main>
  );
}
